export const CLINIC_DATA = {
  name: "Ishwaryam Physiotherapy Speciality Clinic & Rehabilitation Center",
  shortName: "Ishwaryam",
  doctor: {
    name: "Dr. S. Ishwarya",
    qualifications: "B.P.T., M.I.A.P., Hindi B.A.",
    credentialFull: "Bachelor of Physiotherapy | Member, Indian Association of Physiotherapists",
    tagline: "Your Wellness. Our Purpose.",
    taglineTamil: "உங்கள் நலம்... எங்கள் நோக்கம்",
    bio: `Dr. S. Ishwarya founded Ishwaryam Physiotherapy Speciality Clinic with a single conviction — that the people of Gudiyatham deserve world-class rehabilitation without traveling to Chennai or Vellore city. With her Bachelor of Physiotherapy degree and active membership in the Indian Association of Physiotherapists (M.I.A.P.), Dr. Ishwarya brings clinical precision to every assessment, and genuine human care to every session. She does not prescribe generic protocols. She listens. She evaluates. She builds a recovery plan that fits your body, your life, and your goals.`,
  },
  address: {
    line1: "No. 52, Neeli Govindappa Chetty Street (Neeligovindhappan St)",
    line2: "Dharanampet, Near National Higher School, MBS Nagar",
    line3: "Gudiyatham, Vellore District, Tamil Nadu — 632602",
    full: "No. 52, Neeli Govindappa Chetty Street, Dharanampet, Gudiyatham — 632602",
    googleMapsEmbed: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3890.344485361044!2d78.8714!3d12.946!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTLCsDU2JzQ1LjYiTiA3OMKwNTInMTcuMCJF!5e0!3m2!1sen!2sin!4v1712910000000!5m2!1sen!2sin", // Placeholder
  },
  contact: {
    primary: "093614 26487",
    alt: "9843954861",
    whatsapp: "919361426487",
    whatsappLink: "https://wa.me/919361426487",
    email: "ishwaryamphysio@gmail.com",
    youtube: "https://youtube.com/@ishwaryamphysio2687?si=HTg4DojVZGYZm0dh",
  },
  hours: "Monday – Saturday: 9:00 AM – 7:00 PM | Sunday: Closed",
  rating: {
    score: "5.0 / 5.0",
    reviews: "15+ Verified Reviews",
  },
  speciality: "Physiotherapy · Pain Rehabilitation · Neurological Recovery · Sports Medicine",
};

export const SERVICES = [
  {
    title: "Orthopedic Physiotherapy",
    description: "Targeted recovery for fractures, joint replacements, ligament tears, and chronic musculoskeletal dysfunction.",
    icon: "Activity",
  },
  {
    title: "Spine & Back Pain Rehabilitation",
    description: "Disc bulge, PIVD, scoliosis, lumbar spondylosis — addressed at the structural root, not just the symptom.",
    icon: "Stethoscope",
  },
  {
    title: "Neurological Rehabilitation",
    description: "Stroke recovery, Parkinson's management, Bell's palsy — restoring neural pathways through movement science.",
    icon: "Brain",
  },
  {
    title: "Post-Surgical Recovery",
    description: "Structured rehabilitation protocols following orthopedic surgeries to restore full pre-operative function.",
    icon: "ClipboardCheck",
  },
  {
    title: "Sports Injury Treatment",
    description: "From ACL tears to shoulder impingement — return-to-sport programs designed around your performance goals.",
    icon: "Dumbbell",
  },
  {
    title: "Neck Pain & Cervical Spondylosis",
    description: "Manual therapy and targeted mobilization for cervical dysfunction, radiating arm pain, and tension headaches.",
    icon: "PersonStanding",
  },
  {
    title: "Diabetic Neuropathy Management",
    description: "Specialized physiotherapy protocols to manage nerve pain, improve circulation, and restore lower limb function.",
    icon: "Waves",
  },
  {
    title: "Musculoskeletal Therapy",
    description: "Deep tissue techniques, myofascial release, and therapeutic exercise for acute and chronic muscle conditions.",
    icon: "Move",
  },
  {
    title: "Geriatric Physiotherapy",
    description: "Fall prevention, arthritis management, and mobility restoration programs designed specifically for older adults.",
    icon: "Accessibility",
  },
  {
    title: "Pediatric Physiotherapy",
    description: "Developmental delay, cerebral palsy, and postural correction — gentle, play-based rehabilitation for children.",
    icon: "Baby",
  },
  {
    title: "Shoulder, Knee & Hip Joint Pain",
    description: "Biomechanical assessment and precision treatment for the three joints most destroyed by modern sedentary life.",
    icon: "Target",
  },
  {
    title: "Home Visit Physiotherapy",
    description: "Clinic-quality treatment delivered to your home for patients who cannot travel.",
    icon: "Home",
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "BavanaD",
    location: "Gudiyatham",
    rating: 5,
    date: "4 days ago",
    review: "Best service and gud explanation about the condition and treatment... Love the treatment 👌👌",
    highlight: "Best explanation about condition & treatment",
    source: "Google Reviews",
    badge: "Recent",
  },
  {
    id: 2,
    name: "Girija",
    location: "Gudiyatham",
    rating: 5,
    date: "4 days ago",
    review: "Gud treatment and service...best results...thank you 👍",
    highlight: "Best results",
    source: "Google Reviews",
    badge: "Recent",
  },
  {
    id: 3,
    name: "Jothi Nathan",
    location: "Gudiyatham",
    rating: 5,
    date: "5 months ago",
    review: "Excellent service recovered within 5 days after treatment 🙏",
    highlight: "Recovered in just 5 days",
    source: "Google Reviews",
    badge: "Verified",
    featured: true,
  },
  {
    id: 4,
    name: "V. Vaideeswaran",
    location: "Gudiyatham",
    rating: 5,
    date: "3 months ago",
    review: "Excellent treatment 👍👏👏",
    highlight: "Excellent treatment",
    source: "Google Reviews",
    badge: "Verified",
  },
  {
    id: 5,
    name: "Kalim",
    location: "Gudiyatham",
    rating: 5,
    date: "3 months ago",
    review: "Good treatment and service thank you",
    highlight: "Good treatment & service",
    source: "Google Reviews",
    badge: "Verified",
  },
  {
    id: 6,
    name: "Parveen",
    location: "Gudiyatham",
    rating: 5,
    date: "3 years ago",
    review: "Good treatment and service 🙏",
    highlight: "Good treatment & service",
    source: "Google Reviews",
    badge: "Verified",
  },
];
